const NO_IMAGE = '/common/no-avatar.png';

const QUERY_KEYS = {
  PROJECTS: {
    GET_PROJECTS: 'GET_PROJECTS',
    GET_PROJECT_LISTING_INFO: 'GET_PROJECT_LISTING_INFO',
    GET_QUICK_BUY_LISTING_INFO: 'GET_QUICK_BUY_LISTING_INFO',
  },
  COMMON: {
    SEND_FEEDBACK: 'SEND_FEEDBACK',
  },
  USER: {
    GET_WALLET_INFO: 'GET_WALLET_INFO',
    GET_LIST_CARBON: 'GET_LIST_CARBON',
    GET_LIST_TX: 'GET_LIST_TX',
    GET_PROFILE_INFO: 'GET_PROFILE_INFO',
  },
};

export { NO_IMAGE, QUERY_KEYS };
